# Generated by Django 3.2.6 on 2021-08-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_nutrition_saturated_fat_g'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrition',
            name='caffeine_mg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='size_fluid_ounce',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='size_ml',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
    ]
